// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// create_interactions_cpp
Rcpp::List create_interactions_cpp(Rcpp::NumericVector Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericMatrix Xallr, Rcpp::NumericMatrix index_int, Rcpp::NumericVector MI, Rcpp::NumericVector maxcols);
RcppExport SEXP miceadds_create_interactions_cpp(SEXP YrSEXP, SEXP XrSEXP, SEXP XallrSEXP, SEXP index_intSEXP, SEXP MISEXP, SEXP maxcolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xallr(XallrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type index_int(index_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type MI(MISEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type maxcols(maxcolsSEXP);
    __result = Rcpp::wrap(create_interactions_cpp(Yr, Xr, Xallr, index_int, MI, maxcols));
    return __result;
END_RCPP
}
// kernelplsaux
Rcpp::List kernelplsaux(Rcpp::NumericMatrix Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericVector nc);
RcppExport SEXP miceadds_kernelplsaux(SEXP YrSEXP, SEXP XrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nc(ncSEXP);
    __result = Rcpp::wrap(kernelplsaux(Yr, Xr, nc));
    return __result;
END_RCPP
}
// kernelpls_1dim_C
Rcpp::List kernelpls_1dim_C(Rcpp::NumericMatrix Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericVector nc);
RcppExport SEXP miceadds_kernelpls_1dim_C(SEXP YrSEXP, SEXP XrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nc(ncSEXP);
    __result = Rcpp::wrap(kernelpls_1dim_C(Yr, Xr, nc));
    return __result;
END_RCPP
}
// ma_pmm6_C
Rcpp::NumericVector ma_pmm6_C(Rcpp::NumericVector y, Rcpp::NumericVector ry01, Rcpp::NumericMatrix x, double ridge, Rcpp::NumericVector coefu1, Rcpp::NumericVector donorsample);
RcppExport SEXP miceadds_ma_pmm6_C(SEXP ySEXP, SEXP ry01SEXP, SEXP xSEXP, SEXP ridgeSEXP, SEXP coefu1SEXP, SEXP donorsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ry01(ry01SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefu1(coefu1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type donorsample(donorsampleSEXP);
    __result = Rcpp::wrap(ma_pmm6_C(y, ry01, x, ridge, coefu1, donorsample));
    return __result;
END_RCPP
}
// scale2_C
Rcpp::NumericMatrix scale2_C(Rcpp::NumericMatrix x);
RcppExport SEXP miceadds_scale2_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(scale2_C(x));
    return __result;
END_RCPP
}
// scale2_NA_C
Rcpp::NumericMatrix scale2_NA_C(Rcpp::NumericMatrix x);
RcppExport SEXP miceadds_scale2_NA_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    __result = Rcpp::wrap(scale2_NA_C(x));
    return __result;
END_RCPP
}
