//// File Name: RcppExports.cpp
//// File Version: 0.16
// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// create_interactions_cpp
Rcpp::List create_interactions_cpp(Rcpp::NumericVector Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericMatrix Xallr, Rcpp::NumericMatrix index_int, Rcpp::NumericVector MI, Rcpp::NumericVector maxcols);
RcppExport SEXP _miceadds_create_interactions_cpp(SEXP YrSEXP, SEXP XrSEXP, SEXP XallrSEXP, SEXP index_intSEXP, SEXP MISEXP, SEXP maxcolsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xallr(XallrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type index_int(index_intSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type MI(MISEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type maxcols(maxcolsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_interactions_cpp(Yr, Xr, Xallr, index_int, MI, maxcols));
    return rcpp_result_gen;
END_RCPP
}
// kernelplsaux
Rcpp::List kernelplsaux(Rcpp::NumericMatrix Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericVector nc);
RcppExport SEXP _miceadds_kernelplsaux(SEXP YrSEXP, SEXP XrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelplsaux(Yr, Xr, nc));
    return rcpp_result_gen;
END_RCPP
}
// kernelpls_1dim_C
Rcpp::List kernelpls_1dim_C(Rcpp::NumericMatrix Yr, Rcpp::NumericMatrix Xr, Rcpp::NumericVector nc);
RcppExport SEXP _miceadds_kernelpls_1dim_C(SEXP YrSEXP, SEXP XrSEXP, SEXP ncSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nc(ncSEXP);
    rcpp_result_gen = Rcpp::wrap(kernelpls_1dim_C(Yr, Xr, nc));
    return rcpp_result_gen;
END_RCPP
}
// ma_pmm6_C
Rcpp::NumericVector ma_pmm6_C(Rcpp::NumericVector y, Rcpp::NumericVector ry01, Rcpp::NumericMatrix x, double ridge, Rcpp::NumericVector coefu1, Rcpp::NumericVector donorsample);
RcppExport SEXP _miceadds_ma_pmm6_C(SEXP ySEXP, SEXP ry01SEXP, SEXP xSEXP, SEXP ridgeSEXP, SEXP coefu1SEXP, SEXP donorsampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ry01(ry01SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefu1(coefu1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type donorsample(donorsampleSEXP);
    rcpp_result_gen = Rcpp::wrap(ma_pmm6_C(y, ry01, x, ridge, coefu1, donorsample));
    return rcpp_result_gen;
END_RCPP
}
// scale2_C
Rcpp::NumericMatrix scale2_C(Rcpp::NumericMatrix x);
RcppExport SEXP _miceadds_scale2_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scale2_C(x));
    return rcpp_result_gen;
END_RCPP
}
// scale2_NA_C
Rcpp::NumericMatrix scale2_NA_C(Rcpp::NumericMatrix x);
RcppExport SEXP _miceadds_scale2_NA_C(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scale2_NA_C(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_miceadds_create_interactions_cpp", (DL_FUNC) &_miceadds_create_interactions_cpp, 6},
    {"_miceadds_kernelplsaux", (DL_FUNC) &_miceadds_kernelplsaux, 3},
    {"_miceadds_kernelpls_1dim_C", (DL_FUNC) &_miceadds_kernelpls_1dim_C, 3},
    {"_miceadds_ma_pmm6_C", (DL_FUNC) &_miceadds_ma_pmm6_C, 6},
    {"_miceadds_scale2_C", (DL_FUNC) &_miceadds_scale2_C, 1},
    {"_miceadds_scale2_NA_C", (DL_FUNC) &_miceadds_scale2_NA_C, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_miceadds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
