## File Name: RcppExports.R
## File Version: 2.012015
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_interactions_cpp <- function(Yr, Xr, Xallr, index_int, MI, maxcols) {
    .Call('_miceadds_create_interactions_cpp', PACKAGE='miceadds', Yr, Xr, Xallr, index_int, MI, maxcols)
}

kernelplsaux <- function(Yr, Xr, nc) {
    .Call('_miceadds_kernelplsaux', PACKAGE='miceadds', Yr, Xr, nc)
}

kernelpls_1dim_C <- function(Yr, Xr, nc) {
    .Call('_miceadds_kernelpls_1dim_C', PACKAGE='miceadds', Yr, Xr, nc)
}

miceadds_rcpp_ml_mcmc_compute_ztz <- function(Z, idcluster, ncluster) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_compute_ztz', PACKAGE='miceadds', Z, idcluster, ncluster)
}

miceadds_rcpp_ml_mcmc_predict_fixed <- function(X, beta) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_predict_fixed', PACKAGE='miceadds', X, beta)
}

miceadds_rcpp_ml_mcmc_subtract_fixed <- function(y, X, beta) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_subtract_fixed', PACKAGE='miceadds', y, X, beta)
}

miceadds_rcpp_ml_mcmc_predict_random <- function(Z, u, idcluster) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_predict_random', PACKAGE='miceadds', Z, u, idcluster)
}

miceadds_rcpp_ml_mcmc_subtract_random <- function(y, Z, u, idcluster, onlyintercept) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_subtract_random', PACKAGE='miceadds', y, Z, u, idcluster, onlyintercept)
}

miceadds_rcpp_ml_mcmc_sample_beta <- function(xtx_inv, X, Z_list, y, u_list, idcluster_list, sigma2, onlyintercept_list, NR) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_beta', PACKAGE='miceadds', xtx_inv, X, Z_list, y, u_list, idcluster_list, sigma2, onlyintercept_list, NR)
}

miceadds_rcpp_ml_mcmc_sample_u <- function(X, beta, Z_list, y, ztz_list, idcluster_list, ncluster_list, sigma2, Psi_list, onlyintercept_list, NR, u0_list) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_u', PACKAGE='miceadds', X, beta, Z_list, y, ztz_list, idcluster_list, ncluster_list, sigma2, Psi_list, onlyintercept_list, NR, u0_list)
}

miceadds_rcpp_crossprod_one_matrix <- function(X) {
    .Call('_miceadds_miceadds_rcpp_crossprod_one_matrix', PACKAGE='miceadds', X)
}

miceadds_rcpp_ml_mcmc_sample_covariance_matrix <- function(u, nu0, S0) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_covariance_matrix', PACKAGE='miceadds', u, nu0, S0)
}

miceadds_rcpp_ml_mcmc_sample_psi <- function(u_list, nu0_list, S0_list, NR) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_psi', PACKAGE='miceadds', u_list, nu0_list, S0_list, NR)
}

miceadds_rcpp_ml_mcmc_sample_variance <- function(e, nu0, sigma2_0) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_variance', PACKAGE='miceadds', e, nu0, sigma2_0)
}

miceadds_rcpp_ml_mcmc_sample_sigma2 <- function(y, X, beta, Z_list, u_list, idcluster_list, onlyintercept_list, nu0, sigma2_0, NR) {
    .Call('_miceadds_miceadds_rcpp_ml_mcmc_sample_sigma2', PACKAGE='miceadds', y, X, beta, Z_list, u_list, idcluster_list, onlyintercept_list, nu0, sigma2_0, NR)
}

miceadds_rcpp_impute_pmm6 <- function(y, ry01, x, ridge, coefu1, donorsample) {
    .Call('_miceadds_miceadds_rcpp_impute_pmm6', PACKAGE='miceadds', y, ry01, x, ridge, coefu1, donorsample)
}

miceadds_rcpp_mvrnorm <- function(mu, sigma) {
    .Call('_miceadds_miceadds_rcpp_mvrnorm', PACKAGE='miceadds', mu, sigma)
}

miceadds_rcpp_rwishart <- function(df, S) {
    .Call('_miceadds_miceadds_rcpp_rwishart', PACKAGE='miceadds', df, S)
}

miceadds_rcpp_riwishart <- function(df, S) {
    .Call('_miceadds_miceadds_rcpp_riwishart', PACKAGE='miceadds', df, S)
}

miceadds_rcpp_rtnorm_double <- function(mu, sigma, lower, upper) {
    .Call('_miceadds_miceadds_rcpp_rtnorm_double', PACKAGE='miceadds', mu, sigma, lower, upper)
}

miceadds_rcpp_rtnorm <- function(mu, sigma, lower, upper) {
    .Call('_miceadds_miceadds_rcpp_rtnorm', PACKAGE='miceadds', mu, sigma, lower, upper)
}

scale2_C <- function(x) {
    .Call('_miceadds_scale2_C', PACKAGE='miceadds', x)
}

scale2_NA_C <- function(x) {
    .Call('_miceadds_scale2_NA_C', PACKAGE='miceadds', x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_miceadds_RcppExport_registerCCallable', PACKAGE = 'miceadds')
})
