## File Name: RcppExports.R
## File Version: 0.8013
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_interactions_cpp <- function(Yr, Xr, Xallr, index_int, MI, maxcols) {
    .Call('_miceadds_create_interactions_cpp', PACKAGE = 'miceadds', Yr, Xr, Xallr, index_int, MI, maxcols)
}

kernelplsaux <- function(Yr, Xr, nc) {
    .Call('_miceadds_kernelplsaux', PACKAGE = 'miceadds', Yr, Xr, nc)
}

kernelpls_1dim_C <- function(Yr, Xr, nc) {
    .Call('_miceadds_kernelpls_1dim_C', PACKAGE = 'miceadds', Yr, Xr, nc)
}

ma_pmm6_C <- function(y, ry01, x, ridge, coefu1, donorsample) {
    .Call('_miceadds_ma_pmm6_C', PACKAGE = 'miceadds', y, ry01, x, ridge, coefu1, donorsample)
}

scale2_C <- function(x) {
    .Call('_miceadds_scale2_C', PACKAGE = 'miceadds', x)
}

scale2_NA_C <- function(x) {
    .Call('_miceadds_scale2_NA_C', PACKAGE = 'miceadds', x)
}

